---
apiVersion: v1
kind: List
items:
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: mongo
    name: mongo-controller
  spec:
    template:
      metadata:
        labels:
          name: mongo
        name: mongo-controller
      spec:
        containers:
        - image: mongo
          name: mongo
          ports:
          - name: mongo
            containerPort: 27017
          volumeMounts:
              - name: mongo-persistent-storage
                mountPath: /data/db
        volumes:
          - name: mongo-persistent-storage
            persistentVolumeClaim:
              claimName: mongo-persistent-storage
-
  apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    labels:
      name: mongo
    name: mongo
  spec:
    ports:
      - port: 27017
        targetPort: 27017
    selector:
      name: mongo
-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mongo-persistent-storage
  spec:
    accessModes:
     - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
