@startuml

class CheFile {
  - serverConfiguration
  - workspace
}

CheFile o-- "1" CheServerConfiguration
CheFile o-- "1" CheWorkspace

class CheWorkspace {
  - name
  - plugins
  - runtimes
  - commands
  - postloadActions
  - projects
}

together {
  class ChePlugin
  class CheRuntimeEnvironment
  class CheWorkspaceCommand
  class CheWorkspaceProject
}

together {
  class ContainerExec
  class CloudAppDefinition
}

CheWorkspace *-- "n" ChePlugin
CheWorkspace *-- "n" CheRuntimeEnvironment
CheWorkspace *-- "n" CheWorkspaceCommand
CheWorkspace *-- "n" CheWorkspaceProject

class ChePlugin {
    - attributes
    - version
    - dependencies
    - definition
}

class CheRuntimeEnvironment {
    - attributes
    - definition
}


CheRuntimeEnvironment o-- CloudAppDefinition
ChePlugin o-- CloudAppDefinition

CloudAppDefinition <|-.. DockerImage
CloudAppDefinition <|-.. DockerfileLocation
CloudAppDefinition <|-.. Dockerfile
CloudAppDefinition <|-.. Composefile
CloudAppDefinition <|-.. OpenShiftResources
CloudAppDefinition <|-.. KubernetesResources
CloudAppDefinition <|-.. HelmChart

class CheWorkspaceCommand {
  - name
  - type
  - containerExec
  - attributes
}

CheWorkspaceCommand *-- "n" ContainerExec
ContainerExec o-- CheRuntimeEnvironment

class ContainerExec {
  - cloudApp
  - runtime
}

class CheWorkspaceProject {
  - type
  - name
  - source
}

CheWorkspaceProject o-- "1" ProjectSource

class ProjectSource {
  - type
  - location
}

@enduml