@startuml

class CheFile {
  - server
  - workspace
}

CheFile o-- "1" CheServer
CheFile o-- "1" CheWorkspsace

class CheServer {
  - ip
  - port
  - properties
}

class CheWorkspsace {
  - name
  - runtime
  - ram
  - commands
  - postloadActions
  - projects
}

CheWorkspsace o-- "1" DockerRuntime
CheWorkspsace *-- "n" CheWorkspaceCommand
CheWorkspsace *-- "n" CheWorkspacePostLoadAction
CheWorkspsace *-- "n" CheWorkspaceProject

class DockerRuntime {
}

DockerRuntime <|-.. DockerImage
DockerRuntime <|-.. DockerfileLocation
DockerRuntime <|-.. Dockerfile
DockerRuntime <|-.. Composefile

class CheWorkspaceCommand {
  - name
  - type
  - commandLine
  - attributes
}

class CheWorkspacePostLoadAction {
  - command
  - script
}

class CheWorkspaceProject {
  - type
  - name
  - source
}

CheWorkspaceProject o-- "1" ProjectSource

class ProjectSource {
  - type
  - location
}

@enduml