@startuml devfile

class Devfile {
  - specVersion
  - name
  - commands
  - tools
  - projects
}

together {
  class Tool
  class Command
  class Project
}

Devfile *-- "n" Tool
Devfile *-- "n" Command
Devfile *-- "n" Project

class Tool {
    - type
    - alias
}


Tool <|-.. Dockerimage
Tool <|-.. Openshift
Tool <|-.. Kubernetes
Tool <|-.. ChePlugin
Tool <|-.. CheEditor

class Command {
  - name
  - actions
}

Command *-- "n" CommandAction
CommandAction o-- Tool

class CommandAction {
  - type
  - tool
  - command
}

class Project {
  - name
  - source
}

Project o-- "1" ProjectSource

class ProjectSource {
  - type
  - location
}

Project -[hidden]> Tool
Tool -[hidden]> Command
ProjectSource -[hidden]> CommandAction

class Dockerimage {
   - image
   - memoryLimit
   - mountSources
   - volumes
   - env
   - endpoints
   - command
   - args
}

class Openshift {
  - local
  - localContent
  - selector
  - entrypoints
}

class Kubernetes {
  - local
  - localContent
  - selector
  - entrypoints
}

class ChePlugin #yellow {
  - id
}
note bottom of ChePlugin: Che specific

class CheEditor #yellow {
  - id
}
note bottom of CheEditor: Che specific

ChePlugin -[hidden]> CheEditor
CheEditor -[hidden]> Dockerimage

@enduml
